FROM python:3.12-slim

WORKDIR /app

# Copiar apenas requirements necessários
COPY requirements.txt .
RUN pip install --no-cache-dir requests pandas python-dotenv

# Copiar código da ingestão
COPY src/ingestion/ ./src/ingestion/
COPY .env .

CMD ["python", "src/ingestion/fetch_despesas_por_orgao.py"]