FROM python:3.12-slim

WORKDIR /app

# Instalar DuckDB
RUN pip install --no-cache-dir duckdb

# Copiar scripts
COPY scripts/ ./scripts/
COPY data/ ./data/

CMD ["python", "scripts/load_staging_to_duckdb.py"]